workflows:
  flutter-android:
    name: Flutter Android Build
    environment:
      flutter: stable
      java: 17
    working_directory: phon_partes_pp-main
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release -t lib/main.dart
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
